Models/DayResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APIDemo.Models
{
    public class DayResultViewModel
    {
        public string Date { get; set; }
        public bool Holiday { get; set; }
        public string Message { get; set; }
    }
}

Models/DogResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APIDemo.Models
{
    public class DogResponse
    {

        public string Message { get; set; }
        public string Status { get; set; }

    }
}

Models/DogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APIDemo.Models
{
    public class DogViewModel
    {
        public string ImageUrl { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace APIDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GetDayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APIDemo.Models
{
    public class GetDayViewModel
    {
        public DateTime Date { get; set; }
        public bool Holiday { get; set; }

    }
}

Models/RussianHolidayResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace APIDemo.Models
{
    public class RussianHolidayResponse
    {

            public bool Holiday { get; set; }
            public string Date { get; set; }
        public string Message { get; set; }


    }
}

Controllers/DogController.cs
using APIDemo.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace APIDemo.Controllers
{
    public class DogController : Controller
    {
        private readonly IDogFacade _dogFacade;

        public DogController(IDogFacade dogFacade)
        {
            _dogFacade = dogFacade;
        }

        public async Task<IActionResult> Dog()
        {
            var result = await _dogFacade.GetDogViewModel();

            return View(result);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using APIDemo.Models;

namespace APIDemo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RussianHolidayController.cs
using APIDemo.Models;
using APIDemo.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace APIDemo.Controllers
{
    public class RussianHolidayController: Controller
    {
        private readonly IRussianHolidayFacade _russianHolidayFacade;

        public RussianHolidayController(IRussianHolidayFacade russianHolidayFacade)
        {
            _russianHolidayFacade = russianHolidayFacade;
        }

        public IActionResult GetDay()       //DONT FORGET ROUTE-ID IN VIEW
        {                                      //might have to add model

            return View();
        }

        public async Task<IActionResult> DayResult(GetDayViewModel model)
        {
            var result = await _russianHolidayFacade.GetDayResultViewModel(model);
            return View(result);
        }


    }
}

Views/Dog/Dog.cshtml
@model APIDemo.Models.DogViewModel

@{
    ViewData["Title"] = "Dog";
}

<h1>Dog</h1>

<div>
    <h4>DogResponse</h4>
    <img src="@Model.ImageUrl"  />

     
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/RussianHoliday/DayResult.cshtml
@model APIDemo.Models.DayResultViewModel


@{
    ViewData["Title"] = "DayResult";
}

<h1>@Model.Date</h1>

<h1>@Model.Message</h1>


Views/RussianHoliday/GetDay.cshtml
@model APIDemo.Models.GetDayViewModel

@{
    ViewData["Title"] = "GetDay";
}

<h1>GetDay</h1>

<form asp-controller="RussianHoliday" asp-action="DayResult">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Date" class="control-label"></label>
        <input asp-for="Date" asp-route-id="Model.Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-default" />
    </div>
</form>


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APIDemo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APIDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="Dog">Dog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RussianHoliday" asp-action="GetDay">Is It A Russian Holiday?</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - APIDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>